### ISSUE TITLE
Feature planning

### ISSUE THREAD

**Issue by conficient** [aspnet-community-demos/Blazor-Demos#2]
Following on from the [thread](https://github.com/aspnet/Blazor/issues/68) on Blazor, should we list and vote for various features we would all like to see? Perhaps set up a project board for them.

For me, two things I'd like to see:

* how server-side code works, e.g controllers and webapi
* is it possible to create component libraries with Blazor code and include in main lib

**Comment by floreseken** [comment]
Agreed. I'd like to see:

- Routing examples
- Authenmtication
- Unittesting

**Comment by bwjunkie** [comment]
I'd like 
 - WebService connectivity (which return types?)
 - SQLclient (for prototyping / RAD, I think lots of people do it, including me)
 - PDF viewing (sounds off topic, but of great interst as to 'how it will happen')
 - TIF viewing and manipulation

**Comment by grahamehorner** [comment]
@conficient @floreseken I’ve created 3 projects to align with the current blazor projects, a backlog, 0.0.5 and a 0.1.0 where features will be implemented please feel free to raise feature requests as issues, one issue per feature will as much info as possible about usecase and how you see the feature working

**Comment by conficient** [comment]
Thanks @grahamehorner - I'll close this issue and create new ones to map to the backlog.
